### ISSUE TITLE
Drop-down menu for plots

### ISSUE THREAD

**Issue by vbonvin** [vbonvin/POUET#50]
From #26:

Add a right click drop-down menu to chose which plot the user want (airmass, sky chart, etc...). Currently, all the plots open when the user double click on a target, but this is inconvenient since it always want to load the finding chart, which takes time

**Comment by kuntzer** [comment]
Done. Not so easy...

**Comment by vbonvin** [comment]
Looks like you forgot to commit something...;)

FileNotFoundError: [Errno 2] No such file or directory: 'dialogSkyChart.ui'

There's some echo here...

**Comment by vbonvin** [comment]
Looks like you forgot to commit something...;)

FileNotFoundError: [Errno 2] No such file or directory: 'dialogPlots.ui'

**Comment by kuntzer** [comment]
I didn't touch those files which were in the repo for months already :astonished: that's very strange. It's fine on my system as well.

I checked out the git repo in another location and ran main, without any problem. Issue must be on your side.
