### ISSUE TITLE
Pop-up window for Show Selected Names

### ISSUE THREAD

**Issue by vbonvin** [vbonvin/POUET#52]
The current show selected names buttons print the names of the selected targets in the terminal. It should be a pop-up instead, from which the user can copy the list of names.

**Comment by kuntzer** [comment]
Done. Sorry @vbonvin I wanted to do this one :)

**Comment by vbonvin** [comment]
Looks like you forgot to commit something... ;)

FileNotFoundError: [Errno 2] No such file or directory: 'dialogNames.ui'

**Comment by kuntzer** [comment]
It's in the repo already. That's really weird. Could you try to pull again?

**Comment by vbonvin** [comment]
Still not there

**Comment by kuntzer** [comment]
https://github.com/vbonvin/POUET/blob/master/pouet/dialogNames.ui

**Comment by vbonvin** [comment]
Oh, the files are there but are not found by main.py. 

That's probably a path-related issue. Could you make sure that pouet finds them when launching main.py from root?

**Comment by vbonvin** [comment]
Yep that's that, it works when I move in the pouet subfolder.

Mmmh, so it means the load pop-up has the same issue...I wonder if we could import these files as we do with design_scalable.ui

**Comment by vbonvin** [comment]
I found a quick fix:

instead of
>uic.loadUi("dialogPlots.ui")
use
>uic.loadUi(os.path.join(herepath,"dialogPlots.ui"))
with 
> herepath = os.path.dirname(os.path.abspath(inspect.stack()[0][1]))

Will apply that to the other popups load and close the issue
